# The URL the site will be built for
base_url = "https://pitbitdevs.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

title = "BitDevs Pittsburgh"
description = "BitDevs Pittsburgh is a community in the western PA area for those interested in discussing and participating in the research and development of Bitcoin and related protocols."

[extra]
# Put all your custom variables here

github = "https://github.com/pitbitdevs/pitbitdevs.org"
meetup = "https://www.meetup.com/bitdevs-pittsburgh-pitbitdevs-org-meetup-group/"
twitter = "https://www.twitter.com/pitbitdevs"
videos = "https://www.youtube.com"
podcasts = "https://www.podcasts.com"
